# Generated by Django 4.2.5 on 2023-10-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_otp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='email',
        ),
    ]
