# Generated by Django 4.2.5 on 2023-10-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_otp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
