# Generated by Django 4.2.5 on 2023-10-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_otp_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='timestamp',
        ),
    ]
